apiVersion: metering.wbd.com/v1alpha1
kind: CalculationJob
metadata:
  name: test
  description: replace-me-with-your-description
  team: replace-me-with-your-job-team
  id: ae5e920f-1b25-4af9-9a1e-cd7d04f7c0dd
  version: 1
  endpoint: replace-me-with-your-endpoint/v1
  dryRun: false
  needsUsageData: true
  active: true
  notValidBefore: replace-me-with-your-notvalidbefore
  notValidAfter: replace-me-with-your-notvalidbefor
spec:
  usageDataQueries:
    - alias: dataset1
      query: sum(metric) by (omd_component)
    - alias: dataset2
      query: sum(metric2) by (omd_component)
  costDataQueries:
    - alias: costdata1
      query: SELECT SUM(cost) FROM x WHERE tag1='logging-as-a-service' AND tag2='backend-logging'
  calculationQuery: |
    SELECT * from dataset1 as d1 LEFT JOIN dataset2 as d1 ON d1.omd_component = d2.omd_component
