name: pull-request
on:
  pull_request:

jobs:
  pr-title-check:
    name: PR Title Check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
            refactor
            docs
            test
            ci
          scopes: |
            CEA-\d+
          requireScope: true
          ignoreLabels: |
            bot
