name: version-check
on:
  push:
    branches:
      - main
    paths:
      - job-definitions/**
jobs:
  pull-request-version-update-check:
    uses: ./.github/workflows/pull-request-version-update-check.yaml@main
    with:
      path: job-definitions/**
